### ISSUE TITLE
PlotData is outside of GraphView

### ISSUE THREAD

**Issue by magnas35** [KanshuYokoo/SwiftUIGraphPlotLibrary#13]
Hi - I copy/pasted your example code and ran on an iPad simulator. The LinePlot is correct but the other plots appear outside the GraphView.

Funnily enough, when the LinePlot is included (your MultiPlot) everything is good. If the LinePlot is commented out then it fails as described. Any ideas?

**Comment by KanshuYokoo** [comment]
Hi, Thank you for your comment.
I would like to investigate the issue so could you paste your snippet which cause the problem ?

**Comment by KanshuYokoo** [comment]
> Hi, Thank you for your comment.
> I would like to investigate the issue so could you paste your snippet which cause the problem ?

**Comment by KanshuYokoo** [comment]
> Hi, Thank you for your comment.
> I would like to investigate the issue so could you paste your snippet which cause the problem ?

**Comment by KanshuYokoo** [comment]
> Hi - I copy/pasted your example code and ran on an iPad simulator. The LinePlot is correct but the other plots appear outside the GraphView.
> 
> Funnily enough, when the LinePlot is included (your MultiPlot) everything is good. If the LinePlot is commented out then it fails as described. Any ideas?

Hi @magnas35  Thank you.
I would like to investigate your issue so could you please paste your snippet which cause this issue ?

**Comment by magnas35** [comment]
I didn't actually change any of your code, just copy pastedfrom your examples.

`import SwiftUI
import SwiftUIGraphPlotLibrary

struct MultiPlot:View {
    var body:some View {
        let plotset:[PlotData] = [PlotData(x: 0.0,y: 0.0),PlotData(x: 1.0,y: 2.0),PlotData(x: 2.0,y: 5.0),
                                  PlotData(x: 3.0,y: 3.0),PlotData(x: 4.0,y: 8.0),PlotData(x: 5.0,y: 10.0),
                                  PlotData(x: 6.0,y: 25.0),PlotData(x: 7.0,y: 21.0),PlotData(x: 8.0,y: 23.0),
                                  PlotData(x: 9.0,y: 22.0),PlotData(x: 9.6,y: 21.0),PlotData(x: 10,y: 30.0)]
        
        let frameSize = CGSize(width: 300, height: 200)
        let linePLot = GraphPlot(type: .linePlot, color: .orange)
        let barPlot = GraphPlot(type: .verticalBar, color: .blue)
        let bubblePlot = GraphPlot(type: .circlePlot, color: .blue)
            .setCircleRadiusFunc{ index in plotset[index].getY() * 1.4}
            .setHueDegreeFunc{ index in
                                return Double(plotset[index].getY() * 90 / 23)
                              }
        
//        let plotsSet = [linePLot, barPlot,bubblePlot]     <<<<<  Works
//        let plotsSet = [linePLot,bubblePlot]              <<<<<  Works
        let plotsSet = [bubblePlot]   //                    <<<<<  Does not work
        
        return GraphView(dataSet: plotset, plotTypes: plotsSet, frameSize: frameSize, xTicks: true, yTicks: true)
               .frame(width: 350, height: 250, alignment: .center)
    }
}`

When lineplot is used, everything is fine:

![Simulator Screen Shot - iPad Air (4th generation) - 2021-05-30 at 12 13 05](https://user-images.githubusercontent.com/4201689/120101989-d923c580-c140-11eb-8a3c-369247038804.png)

But when lineplot is excluded the plot is askew.

![Simulator Screen Shot - iPad Air (4th generation) - 2021-05-30 at 12 13 31](https://user-images.githubusercontent.com/4201689/120102014-ec369580-c140-11eb-898e-72f05c7ee02e.png)

**Comment by KanshuYokoo** [comment]
I fixed the problem.
Thank you for your pointing to the problem.
