### ISSUE TITLE
Plotting  from array of X and Y values instead of Array of PlotData structures

### ISSUE THREAD

**Issue by ikost** [KanshuYokoo/SwiftUIGraphPlotLibrary#15]
Hi! Thank you for the library - it looks very promising for my projects!

Do you think it makes more sense to provide X and Y values as two separate arrays for plotting LineGraph or even a single array of x,y pairs, rather then the array of PlotData structures? This can be helpful for possible modifications of the dataset i.e. mathematical transformations etc. Please let me know, how do you see it...

**Comment by KanshuYokoo** [comment]
Hi, 
Thank you for the suggestion. 
Plotting with two separate allays would be nice feature.
I will work on it. 

my approgies, I could not answer quickly. 
I would appreciate if you have other issue for some use cases.

**Comment by ikost** [comment]
Hi! Great to see your feedback! The only extra wish nowI have would be  to add the legend to label different datasets. If you agree I can work on it and PR to your repo ?

My concern now is the performance of the library. I need to plot datasets with about 10k (x,y) pairs. In my test after 500 pairs the plot starts to hang in the live preview. Not sure, where is the bottleneck... Any ideas?

**Comment by KanshuYokoo** [comment]
>If you agree I can work on it and PR to your repo ?
Yes, Please feel free to submit PR.

**Comment by KanshuYokoo** [comment]
I have no idea on the performance bottleneck.
I will create the new issue ticket so I will analyse it

**Comment by KanshuYokoo** [comment]
e9909d2

enable the feature to plot with X and Y values as two separate arrays

The simple example is as follows:

```swift
struct arrayPlotInt: View {
    var body: some View {
        
        let xarryInt5:[Int] = [1,2,3,4,5]
        let yarryInt5:[Int] = [1,4,9,16,25]
                
        let bublePlot = GraphPlot(type: .circlePlot, color: .blue)
        
        let frameSize = CGSize(width: 300, height: 200)
        return GraphView(xArray:xarryInt5,yArray:yarryInt5, plotType: bublePlot, frameSize: frameSize, xTicks: true, yTicks: true)
            .frame(width: 350, height: 250, alignment: .center)
    }

}
```
