### ISSUE TITLE
Hang in live preview with a large data set (more than 500)

### ISSUE THREAD

**Issue by KanshuYokoo** [KanshuYokoo/SwiftUIGraphPlotLibrary#16]
The plot starts to hang in the live preview with a large data set (more than 500).

**Comment by KanshuYokoo** [comment]
based on the report from ikost
https://github.com/KanshuYokoo/SwiftUIGraphPlotLibrary/issues/15#issuecomment-900339324

**Comment by KanshuYokoo** [comment]
Hi,
Thank you for the really helpful analysis. 
Would you know which struct of the Library actually the bottleneck caused by init() ?

I am working  on this issue now, I want to keep init method for some of "Struct" .

**Comment by KanshuYokoo** [comment]
I found the real bottleneck.
map function was called in the loop. 
I don't know if calling init() affects the performance. however I think it is good to remove unnecessary init() call to make the code simpler.
I will update the fix branch.

**Comment by KanshuYokoo** [comment]
I will close this 
59e26c6
pull/#22

**Comment by ikost** [comment]
Looks good! I am not 100% sure how SwiftUI handles init() method but my concern is that init() reallocates the memory, which is not needed in SwiftU. Apple claims to specially create bindings and environmental objects to pass the parameters through the views...

**Comment by KanshuYokoo** [comment]
>to specially create bindings and environmental objects to pass the parameters through the views

I see, this will be implemented at the next refactoring. 

The struct is public access when it is a package library, so it is necessary to create a public init() because by the default , structs call private init(). 
I will change it better as Apple suggests.
